### ISSUE TITLE
    Invalid parameter "/1/key_": must contain at least one low-level discovery macro

### ISSUE THREAD

**Issue by jsianard** [bufanda/zabbix--template-xenorchestra#1]
Hello !
I have the following error when importing "    Invalid parameter "/1/key_": must contain at least one low-level discovery macro."

**Comment by bufanda** [comment]
Which Zabbix Version do you use. I use 6.0 LTS currently for development and testing.

**Comment by bufanda** [comment]
I'll need to check if Zabbix changed something in 6.4. that will break the template.

**Comment by bufanda** [comment]
Hm...I have checked. I spun up a  6.4 Container with a copy of my 6.0 Database let it covert the Database and exported the template under 6.4. Deleted the original and tried reimport and it gives me the same error. On 6.0 everything just works. I will have a deeper look in to it what happens.

**Comment by bufanda** [comment]
Found it. The Backup discovery item prototype had not a unique key which needs with LLD macro. Zabbix added a sanity check when importing templates. I pushed an updated template export. It shpould now import without issues in 6.4
