### ISSUE TITLE
Backup jobs status

### ISSUE THREAD

**Issue by ff-ahumberston** [bufanda/zabbix--template-xenorchestra#11]
Updated to the latest version of the template (22/11/24) and noticed that alerts are received for Backup jobs having bad status.

Believe this is connected to the recent change to monitor backups, but it looks to be triggering whilst the backup job is running and resolving upon completion.  Resulting in trigger and resolution for each backup.

**Comment by bufanda** [comment]
Should be fixed wiht 9758bd5
