### ISSUE TITLE
Errors on Discovery

### ISSUE THREAD

**Issue by jmbluethner** [bufanda/zabbix--template-xenorchestra#2]
Hi!

# Description

I'm getting the following error messages on the discovery rules:

```
Cannot execute script: SyntaxError: invalid json (at offset 1)
at [anon] (duktape.c:37568) internal
at parse () native strict preventsyield
at [anon] (function:12) preventsyield
```

![image](https://github.com/bufanda/zabbix--template-xenorchestra/assets/39534549/2d90f5eb-9cb7-45b7-8049-657c66c0d13d)

**Is there any idea on how to solve this issue?**

# Environment

- Zabbix 6.4.13
- XOA 6.1.0-18-amd64 on
- XCP-NG 8.2

**Comment by bufanda** [comment]
I only have tested the templated with XO CE 5.x as far as I know XenOrcestra 6 is still in beta. I will see if I can get a build running and test it meanwhile could you try to get a value block via curl. 

```
curl -b \
    authenticationToken=<auth token> \
    https://<xoaip>/rest/v0/
´´´

**Comment by bufanda** [comment]
I have deployed XOA now on my 8.2 Cluster. I believe you mixed up Version Numbers 6.1.0-18-amd64 is the kernel Version of the OS - XOA is actually 5.93 and I check on my 6.4.13 installation and get all correct data no issues. Please still test with curl if you get a valid json from yout XOA installation.

Also check if macros are set correclty.

For example:

![image](https://github.com/bufanda/zabbix--template-xenorchestra/assets/30717829/d0f073ce-fab4-4df6-a6b6-06363f378641)

**Comment by sblanchouin** [comment]
Hi, 

Same here :

Zabbix 6.4.4
XOA 5.92.1
XCPNG 8.2.1

The curl command : curl -b \
    authenticationToken=<auth token> \
    https://<xoaip>/rest/v0/

Return this : 

[
"/rest/v0/hosts",
"/rest/v0/messages",
"/rest/v0/networks",
"/rest/v0/pools",
"/rest/v0/srs",
"/rest/v0/vbds",
"/rest/v0/vdi-snapshots",
"/rest/v0/vdis",
"/rest/v0/vifs",
"/rest/v0/vm-snapshots",
"/rest/v0/vm-templates",
"/rest/v0/vms",
"/rest/v0/backup",
"/rest/v0/groups",
"/rest/v0/restore",
"/rest/v0/tasks",
"/rest/v0/users"
]


![image](https://github.com/bufanda/zabbix--template-xenorchestra/assets/112562085/1ccc4ba7-9baa-4dc0-80fd-881b3a6b5b02)

Detail of Discovery Host error : 

Cannot execute script: SyntaxError: invalid json (at offset 1)
at [anon] (duktape.c:37568) internal
at parse () native strict preventsyield
at [anon] (function:12) preventsyield

**Comment by bufanda** [comment]
@sblanchouin 
Your curl Request looks good to me. But I can't reproduce the error, could please at the Host go inte the Host Discovery Rule and then click on `Test` and in there on `Get Value`. And See what Value is returned. See image how it should look like.

![image](https://github.com/bufanda/zabbix--template-xenorchestra/assets/30717829/8f39dfa0-3ae0-4be7-b3c2-0f0310133326)

**Comment by sblanchouin** [comment]
Hi, 

I just found my mistake, there was a "/" at the end of my URL!

![image](https://github.com/bufanda/zabbix--template-xenorchestra/assets/112562085/3d248547-a24c-4102-b12b-941f20fec6a9)

By removing it, everything is OK!

![image](https://github.com/bufanda/zabbix--template-xenorchestra/assets/112562085/dd1fb5e4-d63b-4934-b595-95dda96078ae)

Thank you for your help !

**Comment by bufanda** [comment]
Ah, good find. I'll look into if I can add a check for the trailing `/` and remove it before using the macro.

**Comment by sblanchouin** [comment]
I would like to take advantage of this post to congratulate you on your work, it’s really great!

If I may, there is only one thing missing, a trigger on the status of backup jobs ;)

**Comment by bufanda** [comment]
> I would like to take advantage of this post to congratulate you on your work, it’s really great!
> 
> If I may, there is only one thing missing, a trigger on the status of backup jobs ;)

I know, the problem is it's not easy to get the state of a backup as the last run state isn't part of the backup API, but of the task API and getting all tasks and map that to a backup I haven't managed yet as it is a lot of data to process and Zabbix is not really suited to do this. I am still looking for the right inspiration for that. THat's why backup discovery is disabled per default. I already was thinking to remove it again.

**Comment by meekser** [comment]
I get the same issue mentioned few times already:
Cannot execute script: SyntaxError: invalid json (at offset 1)
    at [anon] (duktape.c:37568) internal
    at parse () native strict preventsyield
    at [anon] (function:13) preventsyield
    
Two questions then: 
- does your template work when https is on the self signed cert?
- does it work with proxies?

**Comment by bufanda** [comment]
> I get the same issue mentioned few times already: Cannot execute script: SyntaxError: invalid json (at offset 1) at [anon] (duktape.c:37568) internal at parse () native strict preventsyield at [anon] (function:13) preventsyield
> 
> Two questions then:
> 
> * does your template work when https is on the self signed cert?
> * does it work with proxies?

Proxies I haven't tested but as I haven't implemented the usage of any Proxy into the template it most likely won't work. Also against self-signed certificates I haven't tested. I will check if I can do the requests and ignore certificate validity.

**Comment by bufanda** [comment]
@meekser I added the proxy support with commit  2ecaa37. It isn't tested though as I don't have a setup to test it.
