### ISSUE TITLE
JavaScript syntax errors

### ISSUE THREAD

**Issue by billcouper81** [bufanda/zabbix--template-xenorchestra#3]
Hi.

I just installed this today with the Zabbix 6.4 version template. Error during discovery about missing [ or { near 520.

All of the discovery rule run JavaScript and the if statement that returns 520 is missing {}'s. This in every discovery rule. After wrapping every "return 520" lines in {}'s all discovery rule working.

**Comment by bufanda** [comment]
Weird. It works on my 6.4.17 install just fine. Are you using Zabbix 7? I haven't tested it for Zabbix 7 yet.

**Comment by bufanda** [comment]
I incooparated your suggestion into the template. Hope it will prevent you from editing it if you pull a new version in the future. The commit regard the change is  2ecaa37.
