### ISSUE TITLE
Discovery fails

### ISSUE THREAD

**Issue by MetalSamurai99** [bufanda/zabbix--template-xenorchestra#4]
### Description

Response code "302" did not match any of the required status codes "200"

Attempted to modify the template by changing follow_redirects to 'YES', but still fails to collect any data.

### Environment

Zabbix 7.0.0
XCP-NG 8.2.1
XenOrchestra Community Edition

**Comment by bufanda** [comment]
How did you try to configure follow_redirects? There is no support for redirects in the JavaScript Class.
And there is also no support for it in the template.

https://www.zabbix.com/documentation/current/en/manual/config/items/preprocessing/javascript/javascript_objects

**Comment by MetalSamurai99** [comment]
Using the 6.4 template.

The part that fails is 'Check token validity', starting at line 1069. I tried changing line 1082 which says follow_redirects: 'NO' to YES, but still get the error that the response code 302 does not match the expected 200.

Tried modifying using the GUI 
Select Xen Orchestra by HTTP from templates, click on Web, click on Check Token Validity, then Steps, then Check Token Validity, check the box "Follow redirects", Update and Update again. I don't see any change when it tries again after 5 minutes.

I note the updated template when exported no longer has the follow_redirects line at all, but 302 is a temporary redirect. 

Only installed Zabbix a couple of days ago, so I have no idea what's going wrong.

**Comment by bufanda** [comment]
Ah got you. That's not a one of the Script Item but the Web Scenario. What does you {$XOA.URL} look like? 
Do you use `http://` instead of `https://` for the macro but Xen-Orchestra is using https and you redirect from http to https?
Could you try https? Could be a Zabbix issue then.

**Comment by MetalSamurai99** [comment]
The URL I'm using is 

https://xo-host.fullyqualified.com/

I haven't tried https://xo-host/ or https://xxx.xxx.xxx.xxx/ it's possible that one of those names/IP address would avoid the redirection. I haven't dug in to how XenOrchestra is set up. Just used the automated build script for the community edition. In any case, that seems like the wrong fix. The test is just "is this token correct?" (And I'm pretty sure it is), but instead of getting a 200 code back from XO it's a 302 redirect.

**Comment by billcouper81** [comment]
It working for me on Zabbix 7.0.3, with XCP-ng 8.2.1, and Xen Orchestra Appliance 5.95.2

My web scenario for 'check token validity' looks like this:
`URL = {$XOA.URL}/rest/v0`

And I have defined that macro on the host object as:
`{$XOA.URL} = https://xoaname.fqdn.com`

Note that I don't have a trailing slash on my macro definition, which would cause a double-slash in the web scenario... could it be as simple as that?

**Comment by bufanda** [comment]
> It working for me on Zabbix 7.0.3, with XCP-ng 8.2.1, and Xen Orchestra Appliance 5.95.2
> 
> My web scenario for 'check token validity' looks like this: `URL = {$XOA.URL}/rest/v0`
> 
> And I have defined that macro on the host object as: `{$XOA.URL} = https://xoaname.fqdn.com`
> 
> Note that I don't have a trailing slash on my macro definition, which would cause a double-slash in the web scenario... could it be as simple as that?

Probably, the trailing slash already caused issues with discovery rules that's why it is stripped, but this is not possible in web scenarios. Need to try it and see if that's the root cause.
